//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotersEDM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ncvoter40
    {
        public string county_id { get; set; }
        public string county_desc { get; set; }
        public string voter_reg_num { get; set; }
        public string status_cd { get; set; }
        public string voter_status_desc { get; set; }
        public string reason_cd { get; set; }
        public string voter_status_reason_desc { get; set; }
        public string absent_ind { get; set; }
        public string name_prefx_cd { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string name_suffix_lbl { get; set; }
        public string res_street_address { get; set; }
        public string res_city_desc { get; set; }
        public string state_cd { get; set; }
        public string zip_code { get; set; }
        public string mail_addr1 { get; set; }
        public string mail_addr2 { get; set; }
        public string mail_addr3 { get; set; }
        public string mail_addr4 { get; set; }
        public string mail_city { get; set; }
        public string mail_state { get; set; }
        public string mail_zipcode { get; set; }
        public string full_phone_number { get; set; }
        public string race_code { get; set; }
        public string ethnic_code { get; set; }
        public string party_cd { get; set; }
        public string gender_code { get; set; }
        public string birth_age { get; set; }
        public string birth_state { get; set; }
        public string drivers_lic { get; set; }
        public string registr_dt { get; set; }
        public string precinct_abbrv { get; set; }
        public string precinct_desc { get; set; }
        public string municipality_abbrv { get; set; }
        public string municipality_desc { get; set; }
        public string ward_abbrv { get; set; }
        public string ward_desc { get; set; }
        public string cong_dist_abbrv { get; set; }
        public string super_court_abbrv { get; set; }
        public string judic_dist_abbrv { get; set; }
        public string nc_senate_abbrv { get; set; }
        public string nc_house_abbrv { get; set; }
        public string county_commiss_abbrv { get; set; }
        public string county_commiss_desc { get; set; }
        public string township_abbrv { get; set; }
        public string township_desc { get; set; }
        public string school_dist_abbrv { get; set; }
        public string school_dist_desc { get; set; }
        public string fire_dist_abbrv { get; set; }
        public string fire_dist_desc { get; set; }
        public string water_dist_abbrv { get; set; }
        public string water_dist_desc { get; set; }
        public string sewer_dist_abbrv { get; set; }
        public string sewer_dist_desc { get; set; }
        public string sanit_dist_abbrv { get; set; }
        public string sanit_dist_desc { get; set; }
        public string rescue_dist_abbrv { get; set; }
        public string rescue_dist_desc { get; set; }
        public string munic_dist_abbrv { get; set; }
        public string munic_dist_desc { get; set; }
        public string dist_1_abbrv { get; set; }
        public string dist_1_desc { get; set; }
        public string dist_2_abbrv { get; set; }
        public string dist_2_desc { get; set; }
        public string confidential_ind { get; set; }
        public string birth_year { get; set; }
        public string ncid { get; set; }
        public string vtd_abbrv { get; set; }
        public string vtd_desc { get; set; }
        [Key]
        public long ID { get; set; }
    }
}
