//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotersEDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class VotersDBEntities : DbContext
    {
        public VotersDBEntities() : base("name=VotersDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<ChangeLog> ChangeLogs { get; set; }
        public virtual DbSet<ncvoter40> ncvoter40 { get; set; }
    }
}
